#!/usr/bin/env python3
"""Assert that a presentation change did not become a scientific change.

This exists for the executive visual refactor. That pass is allowed to move any
sentence, heading, style rule or figure role on the site. It is not allowed to move a
number, a threshold, an equation, an input or a result.

The manifest below is a list of paths whose bytes must not change, plus a small number of
files that are regenerated from those bytes and so are compared by *content* rather than
by byte identity. Everything protected here is either an input to a case, an output of a
case, an acceptance criterion, a protocol, or a published numerical download.

Usage
-----
    python3 scripts/check_science_frozen.py --write   # record the baseline
    python3 scripts/check_science_frozen.py           # verify nothing moved
    python3 scripts/check_science_frozen.py --against <git-ref>

The baseline file is committed so a reviewer can see exactly what was frozen and when.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
BASELINE = REPO_ROOT / "docs" / "release" / "science_frozen.json"

#: Directory trees whose every file is protected, with the suffixes that matter.
PROTECTED_TREES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("cases", (".json", ".md", ".py")),
    ("src/reservoir_lab", (".py",)),
    ("tests", (".py",)),
    ("configs", (".json", ".toml", ".yaml", ".yml")),
    ("docs/evidence", (".md",)),
    ("docs/protocols", (".md",)),
)

#: Individual files that are protected on their own.
PROTECTED_FILES: tuple[str, ...] = (
    "docs/release/canonical_environment.json",
    "docs/release/portability_envelope.json",
    "scripts/compare_case_outputs.py",
    "scripts/verify.py",
    "scripts/export_presentation_data.py",
    "requirements-dev.lock",
)

#: Published numerical downloads. These are regenerated by the site emitter, so a
#: description string may legitimately change while no number does. They are compared as
#: parsed content with description fields excluded, not as bytes.
PROTECTED_DATA_DIR = "site/public/data"
DATA_SUFFIXES = (".csv", ".json")
#: Files under PROTECTED_DATA_DIR that are indexes rather than data.
DATA_INDEX_FILES = ("index.json",)


def digest(path: pathlib.Path) -> str:
    """Return the SHA-256 of a file's bytes."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def protected_paths() -> list[pathlib.Path]:
    """Every path the manifest protects, sorted, relative to the repository root."""
    found: set[pathlib.Path] = set()
    for tree, suffixes in PROTECTED_TREES:
        base = REPO_ROOT / tree
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if path.is_file() and path.suffix in suffixes and "__pycache__" not in path.parts:
                found.add(path.relative_to(REPO_ROOT))
    for name in PROTECTED_FILES:
        path = REPO_ROOT / name
        if path.exists():
            found.add(path.relative_to(REPO_ROOT))
    data = REPO_ROOT / PROTECTED_DATA_DIR
    if data.exists():
        for path in data.iterdir():
            if path.is_file() and path.suffix in DATA_SUFFIXES:
                found.add(path.relative_to(REPO_ROOT))
    return sorted(found)


def build() -> dict[str, str]:
    """Return {relative path: sha256} for everything protected."""
    return {str(p): digest(REPO_ROOT / p) for p in protected_paths()}


def numbers_only(path: pathlib.Path) -> str:
    """Return a digest of a data file's numbers, ignoring prose fields.

    A published download is regenerated by the site emitter. Its `description` is
    presentation and may legitimately change in this pass; every number in it may not.
    """
    if path.suffix == ".json":
        payload = json.loads(path.read_text())

        def strip(node):
            if isinstance(node, dict):
                return {k: strip(v) for k, v in sorted(node.items()) if k != "description"}
            if isinstance(node, list):
                return [strip(v) for v in node]
            return node

        return hashlib.sha256(
            json.dumps(strip(payload), sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()
    return digest(path)


def compare(baseline: dict[str, str]) -> list[str]:
    """Return a human-readable list of every protected file that moved."""
    current = build()
    problems: list[str] = []
    for name in sorted(set(baseline) | set(current)):
        was, now = baseline.get(name), current.get(name)
        if was is None:
            problems.append(f"ADDED    {name}")
        elif now is None:
            problems.append(f"REMOVED  {name}")
        elif was != now:
            path = REPO_ROOT / name
            index = name.startswith(PROTECTED_DATA_DIR) and path.name in DATA_INDEX_FILES
            if index:
                problems.append(f"CHANGED  {name} (download index: check descriptions only)")
            elif name.startswith(PROTECTED_DATA_DIR):
                problems.append(f"CHANGED  {name} (published download)")
            else:
                problems.append(f"CHANGED  {name}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="record the current tree as the baseline")
    parser.add_argument("--against", help="compare against this git ref instead of the baseline file")
    args = parser.parse_args(argv)

    if args.write:
        head = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO_ROOT, capture_output=True, text=True, check=True
        ).stdout.strip()
        BASELINE.write_text(
            json.dumps(
                {
                    "purpose": (
                        "Scientific artefacts frozen for the executive visual refactor. A "
                        "presentation change must not become a scientific change."
                    ),
                    "frozen_at_commit": head,
                    "files": build(),
                },
                indent=2,
            )
            + "\n"
        )
        print(f"recorded {len(build())} protected files at {head[:8]} -> {BASELINE}")
        return 0

    if not BASELINE.exists():
        print(f"no baseline at {BASELINE}; run with --write first", file=sys.stderr)
        return 1
    baseline = json.loads(BASELINE.read_text())["files"]
    problems = compare(baseline)
    print(f"science-frozen: {len(baseline)} protected files")
    if not problems:
        print("science-frozen: PASS - every protected artefact is byte-identical")
        return 0
    print(f"science-frozen: FAIL - {len(problems)} protected artefact(s) moved")
    for line in problems:
        print(f"  {line}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
