#!/usr/bin/env python3
"""Case B1 -- infinite-acting radial flow, known answer.

Runs the four experiments pre-registered in ``protocol.md``, which was committed before
this file existed. Nothing here chooses a threshold: every acceptance number is copied
from the protocol and is checked against results it was written before.

    PYTHONPATH=src python3 cases/B1_iarf_known_answer/run.py --out artifacts/B1_iarf_known_answer/run-001

The study is the transient analogue of A1. A synthetic drawdown is generated from the
line-source solution at declared properties, and a semilog straight line is asked to
recover the permeability and skin that generated it. The generator evaluates a special
function; the interpreter fits a line on a logarithmic axis and is never told the
answer. Where they agree, the agreement is evidence about the instrument. Where the
interpreter is pointed outside its valid window it is expected to fail, and B1.3 exists
to show the acceptance machinery refusing a result that still looks like a straight line.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import pathlib
import random
import statistics
import sys
from typing import Any

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

from reservoir_lab.diagnostics import bourdet_derivative  # noqa: E402
from reservoir_lab.provenance import RunRecord  # noqa: E402
from reservoir_lab.transient import (  # noqa: E402
    LINE_SOURCE_CONSTANT,
    derivative_plateau_constant,
    dimensionless_time,
    exponential_integral_e1,
    line_source_dimensionless_pressure,
    line_source_log_derivative,
    pressure_drop_psi,
    semilog_interpretation,
    semilog_skin_constant,
    semilog_slope_constant,
)

CASE_ID = "B1_iarf_known_answer"

#: The commit that introduced protocol.md, before this file existed. Section 7 of the
#: protocol requires it to appear in the run record so the chronology is checkable from
#: the result rather than taken on trust.
PROTOCOL_COMMIT = "f308adcad51997a3e05f99a3f60c433fc97e2bf7"
PROTOCOL_PATH = REPO_ROOT / "cases" / "B1_iarf_known_answer" / "protocol.md"


def protocol_digest() -> str:
    """Return the git blob digest of the protocol, computed at run time.

    Computed rather than stored, so that editing the protocol after results exist shows
    up as a changed digest in every later run record instead of passing unnoticed. The
    algorithm is git's own blob hash, so the value can be checked with
    ``git hash-object cases/B1_iarf_known_answer/protocol.md``.
    """
    raw = PROTOCOL_PATH.read_bytes()
    return hashlib.sha1(b"blob %d\x00" % len(raw) + raw).hexdigest()


# ---------------------------------------------------------------------------------
# Protocol section 2. The declared truth. The interpreter never sees these.
# ---------------------------------------------------------------------------------
TRUTH = {
    "permeability_md": 50.0,
    "thickness_ft": 40.0,
    "porosity": 0.18,
    "total_compressibility_per_psi": 1.5e-5,
    "viscosity_cp": 1.2,
    "formation_volume_factor": 1.25,
    "wellbore_radius_ft": 0.35,
    "initial_pressure_psia": 4000.0,
    "rate_stb_per_day": 350.0,
    "skin": 3.5,
    "wellbore_storage_bbl_per_psi": 0.0,
}

# Protocol section 4. Declared before results and not moved after them.
WINDOW_FIRST_HOUR = 1.0
WINDOW_LAST_HOUR = 48.0
BASE_POINTS_PER_DECADE = 50
SMOOTHING_L = 0.1

# Protocol section 5. Seeds fixed in the protocol; not drawn here.
NOISE_SIGMAS_PSI = (0.1, 0.5, 2.0, 10.0)
NOISE_REPLICATES = 200
NOISE_SEED_BASE = 20260915
SAMPLING_POINTS_PER_DECADE = (2, 3, 5, 10, 20, 50, 200)
# Exactly the six starts the protocol declares. The last is the declared
# interpretation window itself, quoted there to three significant figures.
WINDOW_START_T_D = (10.0, 25.0, 50.0, 100.0, 1000.0, 3.32e4)
NEGATIVE_CONTROL_T_D = (1.0, 10.0)

# Protocol section 6. Thresholds, copied verbatim. Not derived here and not adjusted.
C1_FORWARD_ORACLE_RELATIVE = 1e-12
C2_CONSTANT_RELATIVE = 1e-4
C3_KH_RELATIVE = 1e-4
C4_SKIN_ABSOLUTE = 1e-3
C5_DERIVATIVE_RELATIVE = 1e-6
C7_NEGATIVE_CONTROL_MIN_KH_ERROR = 1e-4

LIMITATIONS = (
    "Synthetic throughout. No field data, no gauge, no real well.",
    "One model: homogeneous, isotropic, infinite-acting, single phase, constant rate, "
    "zero wellbore storage. Nothing here establishes behaviour outside it.",
    "Wellbore storage is zero by declared design. Real early-time data is distorted by "
    "storage and that distortion interacts with skin; B2 covers it.",
    "Constant fluid properties. Real-gas pseudopressure and pseudotime are B4.",
    "The independence in B1 is between the forward and inverse methods, not between "
    "this project and the world. The data were generated by a solution this project "
    "implemented.",
    "No comparison against any commercial well-test package has been performed.",
)


def canonical_hash(payload: Any) -> str:
    """Return a stable digest of a JSON-serialisable payload."""
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":"), default=repr).encode()
    ).hexdigest()


def t_d(hours: float) -> float:
    """Dimensionless time at the declared properties."""
    return dimensionless_time(
        hours,
        permeability_md=TRUTH["permeability_md"],
        porosity=TRUTH["porosity"],
        viscosity_cp=TRUTH["viscosity_cp"],
        total_compressibility_per_psi=TRUTH["total_compressibility_per_psi"],
        wellbore_radius_ft=TRUTH["wellbore_radius_ft"],
    )


def hours_at_t_d(target: float) -> float:
    """Elapsed time in hours at which dimensionless time reaches ``target``."""
    return (
        target
        * TRUTH["porosity"]
        * TRUTH["viscosity_cp"]
        * TRUTH["total_compressibility_per_psi"]
        * TRUTH["wellbore_radius_ft"] ** 2
    ) / (0.0002637 * TRUTH["permeability_md"])


def drawdown_psi(hours: float) -> float:
    """Return the synthetic observation: drawdown from initial pressure, in psi."""
    return pressure_drop_psi(
        line_source_dimensionless_pressure(t_d(hours), skin=TRUTH["skin"]),
        permeability_md=TRUTH["permeability_md"],
        thickness_ft=TRUTH["thickness_ft"],
        rate_stb_per_day=TRUTH["rate_stb_per_day"],
        formation_volume_factor=TRUTH["formation_volume_factor"],
        viscosity_cp=TRUTH["viscosity_cp"],
    )


def log_window(first: float, last: float, per_decade: int) -> list[float]:
    """Return logarithmically spaced times, inclusive of both ends."""
    decades = math.log10(last) - math.log10(first)
    count = max(3, round(per_decade * decades) + 1)
    return [10 ** (math.log10(first) + i * decades / (count - 1)) for i in range(count)]


def interpret(times: list[float], drops: list[float]) -> Any:
    """Run the blind semilog interpretation at the declared well and fluid properties."""
    return semilog_interpretation(
        times,
        drops,
        thickness_ft=TRUTH["thickness_ft"],
        rate_stb_per_day=TRUTH["rate_stb_per_day"],
        formation_volume_factor=TRUTH["formation_volume_factor"],
        viscosity_cp=TRUTH["viscosity_cp"],
        porosity=TRUTH["porosity"],
        total_compressibility_per_psi=TRUTH["total_compressibility_per_psi"],
        wellbore_radius_ft=TRUTH["wellbore_radius_ft"],
    )


def recovery_errors(fit: Any) -> tuple[float, float]:
    """Return ``(relative kh error, absolute skin error)`` against the declared truth."""
    kh_true = TRUTH["permeability_md"] * TRUTH["thickness_ft"]
    return (
        abs(fit.permeability_thickness_md_ft - kh_true) / kh_true,
        abs(fit.skin - TRUTH["skin"]),
    )


# ---------------------------------------------------------------------------------
# B1.0 -- mathematical baseline
# ---------------------------------------------------------------------------------
def experiment_b1_0() -> dict[str, Any]:
    """Noise-free recovery over the declared window, plus the forward and constant checks."""
    # C2: every published field constant, recomputed.
    # Each published constant is compared at the precision it is actually printed to.
    # A single relative tolerance is the wrong instrument here: 162.6 carries four
    # significant figures and 3.2275 carries five, so one tolerance is either too loose
    # for one or too tight for the other. The literature also truncates as often as it
    # rounds -- 0.80907 is a truncation of 0.8090787, which rounds to 0.80908 -- so the
    # test is agreement within one unit in the last printed digit, which both a rounded
    # and a truncated form satisfy and a genuinely wrong constant does not.
    constants = (
        ("line_source_0_80907", LINE_SOURCE_CONSTANT, "0.80907"),
        ("semilog_slope_162_6", semilog_slope_constant(), "162.6"),
        ("derivative_plateau_70_6", derivative_plateau_constant(), "70.6"),
        ("skin_3_2275", semilog_skin_constant(), "3.2275"),
    )
    constant_rows = []
    for name, derived, printed in constants:
        decimals = len(printed.split(".")[1]) if "." in printed else 0
        last_digit_unit = 10.0**-decimals
        difference = abs(derived - float(printed))
        constant_rows.append(
            {
                "name": name,
                "derived": derived,
                "published_as_printed": printed,
                "printed_decimals": decimals,
                "last_digit_unit": last_digit_unit,
                "absolute_difference": difference,
                "within_published_precision": difference <= last_digit_unit,
            }
        )

    # C1: the forward solution against the arbitrary-precision oracle, in B1's own range.
    oracle_rows = []
    for hours in (1.0, 4.0, 12.0, 24.0, 48.0):
        argument = 1.0 / (4.0 * t_d(hours))
        oracle_rows.append(
            {
                "time_hours": hours,
                "dimensionless_time": t_d(hours),
                "e1_argument": argument,
                "e1_float": exponential_integral_e1(argument),
                "e1_high_precision": _e1_high_precision(argument),
                "relative_difference": abs(exponential_integral_e1(argument) - _e1_high_precision(argument))
                / abs(_e1_high_precision(argument)),
            }
        )

    times = log_window(WINDOW_FIRST_HOUR, WINDOW_LAST_HOUR, BASE_POINTS_PER_DECADE)
    drops = [drawdown_psi(t) for t in times]
    fit = interpret(times, drops)
    kh_error, skin_error = recovery_errors(fit)

    # C5 and C6: the Bourdet derivative against the closed form, and against 1/2.
    scale = pressure_drop_psi(
        1.0,
        permeability_md=TRUTH["permeability_md"],
        thickness_ft=TRUTH["thickness_ft"],
        rate_stb_per_day=TRUTH["rate_stb_per_day"],
        formation_volume_factor=TRUTH["formation_volume_factor"],
        viscosity_cp=TRUTH["viscosity_cp"],
    )
    deriv_times, deriv_values = bourdet_derivative(times, drops, smoothing_l=SMOOTHING_L)
    analytic = [line_source_log_derivative(t_d(t)) * scale for t in deriv_times]
    derivative_errors = [abs(d - a) / a for d, a in zip(deriv_values, analytic, strict=True)]
    ideal_plateau = 0.5 * scale
    plateau_deficits = [(ideal_plateau - d) / ideal_plateau for d in deriv_values]

    # The series the figures draw. Exported from the audited run rather than recomputed
    # by the renderer, so that what a reader sees and what the acceptance criteria were
    # applied to are the same numbers.
    fitted_line = [fit.intercept_psi + fit.slope_psi_per_cycle * math.log10(t) for t in times]
    series = {
        "time_hours": list(times),
        "dimensionless_time": [t_d(t) for t in times],
        "drawdown_psi": list(drops),
        "fitted_line_psi": fitted_line,
        "residual_psi": [d - f for d, f in zip(drops, fitted_line, strict=True)],
        "derivative_time_hours": list(deriv_times),
        "derivative_psi": list(deriv_values),
        "analytic_derivative_psi": list(analytic),
    }

    return {
        "series": series,
        "window": {
            "first_hour": WINDOW_FIRST_HOUR,
            "last_hour": WINDOW_LAST_HOUR,
            "first_dimensionless_time": t_d(WINDOW_FIRST_HOUR),
            "last_dimensionless_time": t_d(WINDOW_LAST_HOUR),
            "points_per_decade": BASE_POINTS_PER_DECADE,
            "points": len(times),
        },
        "derived_constants": constant_rows,
        "forward_against_oracle": oracle_rows,
        "max_forward_relative_difference": max(r["relative_difference"] for r in oracle_rows),
        "fit": {
            "slope_psi_per_cycle": fit.slope_psi_per_cycle,
            "intercept_psi": fit.intercept_psi,
            "pressure_drop_at_one_hour_psi": fit.pressure_drop_at_one_hour,
            "r_squared": fit.r_squared,
            "residual_standard_error_psi": fit.residual_standard_error_psi,
        },
        "recovery": {
            "permeability_md_true": TRUTH["permeability_md"],
            "permeability_md_recovered": fit.permeability_md,
            "permeability_thickness_true": TRUTH["permeability_md"] * TRUTH["thickness_ft"],
            "permeability_thickness_recovered": fit.permeability_thickness_md_ft,
            "permeability_thickness_relative_error": kh_error,
            "skin_true": TRUTH["skin"],
            "skin_recovered": fit.skin,
            "skin_absolute_error": skin_error,
        },
        "derivative": {
            "smoothing_l": SMOOTHING_L,
            "points": len(deriv_values),
            "max_relative_error_against_closed_form": max(derivative_errors),
            "median_relative_error_against_closed_form": statistics.median(derivative_errors),
            "ideal_plateau_psi": ideal_plateau,
            "mean_measured_plateau_psi": statistics.fmean(deriv_values),
            "max_deficit_from_ideal_relative": max(plateau_deficits),
            "min_deficit_from_ideal_relative": min(plateau_deficits),
            "all_below_ideal": all(d < ideal_plateau for d in deriv_values),
        },
        "c1_forward_matches_oracle": max(r["relative_difference"] for r in oracle_rows)
        <= C1_FORWARD_ORACLE_RELATIVE,
        "c2_constants_reproduce": all(r["within_published_precision"] for r in constant_rows),
        "c3_kh_recovered": kh_error <= C3_KH_RELATIVE,
        "c4_skin_recovered": skin_error <= C4_SKIN_ABSOLUTE,
        "c5_derivative_matches_closed_form": max(derivative_errors) <= C5_DERIVATIVE_RELATIVE,
        "c6_plateau_below_ideal_half": all(d < ideal_plateau for d in deriv_values),
    }


def _e1_high_precision(x: float, digits: int = 40) -> float:
    """Oracle O1. Declared valid for x <= 2, which contains the whole B1 window."""
    from decimal import Decimal, getcontext

    if x > 2.0:
        raise ValueError("oracle O1 is declared valid only for x <= 2")
    getcontext().prec = digits + 25
    value = Decimal(repr(x))
    gamma = Decimal("0.5772156649015328606065120900824024310421593359399235988057672348849")
    total = Decimal(0)
    term = Decimal(1)
    for n in range(1, 400):
        term *= -value / n
        total += -term / n
        if abs(term / n) < Decimal(10) ** (-(digits + 15)):
            break
    return float(-gamma - value.ln() + total)


# ---------------------------------------------------------------------------------
def _projected_placement_bias(start_t_d: float) -> float:
    """Least-squares projection of the semilog departure onto the fitted line.

    POST-HOC DIAGNOSTIC. Not pre-registered, not gated, and it moves no threshold.

    The line-source solution departs from its own semilog asymptote by exactly
    ``1/(8 t_D)`` (evidence card section 2). The protocol predicted the resulting
    permeability bias as ``1/(10 t_D,min)``, which is the departure at the *first*
    point of the window. A least-squares slope does not see the first point; it sees
    the covariance of the departure with ``ln t`` over the whole window. This function
    computes that projection on the same discrete grid the sweep uses, so the reported
    scaling can be checked rather than asserted.
    """
    first = hours_at_t_d(start_t_d)
    times = log_window(first, first * (WINDOW_LAST_HOUR / WINDOW_FIRST_HOUR), BASE_POINTS_PER_DECADE)
    u = [math.log(t_d(t)) for t in times]
    departure = [1.0 / (8.0 * math.exp(x)) for x in u]
    n = len(u)
    mean_u = math.fsum(u) / n
    mean_d = math.fsum(departure) / n
    covariance = math.fsum((a - mean_u) * (b - mean_d) for a, b in zip(u, departure, strict=True)) / n
    variance = math.fsum((a - mean_u) ** 2 for a in u) / n
    # The true dimensionless semilog slope is 1/2, and kh is inversely proportional to
    # the fitted slope, so a slope bias of dm maps to a relative kh error of dm / (1/2).
    return abs((covariance / variance) / 0.5)


# B1.1 -- sampling density and window placement
# ---------------------------------------------------------------------------------
def experiment_b1_1() -> dict[str, Any]:
    """Which of point density and window placement actually limits a clean interpretation."""
    density_rows = []
    for per_decade in SAMPLING_POINTS_PER_DECADE:
        times = log_window(WINDOW_FIRST_HOUR, WINDOW_LAST_HOUR, per_decade)
        fit = interpret(times, [drawdown_psi(t) for t in times])
        kh_error, skin_error = recovery_errors(fit)
        density_rows.append(
            {
                "points_per_decade": per_decade,
                "points": len(times),
                "permeability_thickness_relative_error": kh_error,
                "skin_absolute_error": skin_error,
            }
        )

    placement_rows = []
    for start_t_d in WINDOW_START_T_D:
        first = hours_at_t_d(start_t_d)
        last = first * (WINDOW_LAST_HOUR / WINDOW_FIRST_HOUR)
        times = log_window(first, last, BASE_POINTS_PER_DECADE)
        fit = interpret(times, [drawdown_psi(t) for t in times])
        kh_error, skin_error = recovery_errors(fit)
        placement_rows.append(
            {
                "window_start_dimensionless_time": start_t_d,
                "first_hour": first,
                "last_hour": last,
                "permeability_thickness_relative_error": kh_error,
                "skin_absolute_error": skin_error,
                # The protocol predicted this scale before the run.
                "predicted_bias_one_over_ten_t_d": 1.0 / (10.0 * start_t_d),
                # Post-hoc, ungated: see _projected_placement_bias.
                "projected_bias_least_squares": _projected_placement_bias(start_t_d),
            }
        )

    density_spread = max(r["permeability_thickness_relative_error"] for r in density_rows) / min(
        r["permeability_thickness_relative_error"] for r in density_rows
    )
    placement_spread = max(r["permeability_thickness_relative_error"] for r in placement_rows) / min(
        r["permeability_thickness_relative_error"] for r in placement_rows
    )
    return {
        "density_sweep": density_rows,
        "placement_sweep": placement_rows,
        "density_error_spread_ratio": density_spread,
        "placement_error_spread_ratio": placement_spread,
        "placement_dominates": placement_spread > density_spread,
    }


# ---------------------------------------------------------------------------------
# B1.2 -- pressure noise
# ---------------------------------------------------------------------------------
def experiment_b1_2() -> dict[str, Any]:
    """Degradation under additive Gaussian pressure error, over fixed seeds."""
    times = log_window(WINDOW_FIRST_HOUR, WINDOW_LAST_HOUR, BASE_POINTS_PER_DECADE)
    clean = [drawdown_psi(t) for t in times]
    rows = []
    for sigma in NOISE_SIGMAS_PSI:
        kh_errors: list[float] = []
        skin_errors: list[float] = []
        for replicate in range(NOISE_REPLICATES):
            rng = random.Random(NOISE_SEED_BASE + replicate)
            noisy = [value + rng.gauss(0.0, sigma) for value in clean]
            fit = interpret(times, noisy)
            kh_error, skin_error = recovery_errors(fit)
            kh_errors.append(kh_error)
            skin_errors.append(skin_error)
        kh_sorted = sorted(kh_errors)
        skin_sorted = sorted(skin_errors)
        p95 = int(0.95 * (NOISE_REPLICATES - 1))
        rows.append(
            {
                "sigma_psi": sigma,
                "replicates": NOISE_REPLICATES,
                "seed_base": NOISE_SEED_BASE,
                "kh_relative_error_mean": statistics.fmean(kh_errors),
                "kh_relative_error_p95": kh_sorted[p95],
                # Monte Carlo standard error of the mean, which is a property of the
                # replicate count and not an uncertainty about the reservoir.
                "kh_relative_error_monte_carlo_se": statistics.stdev(kh_errors) / math.sqrt(NOISE_REPLICATES),
                "skin_absolute_error_mean": statistics.fmean(skin_errors),
                "skin_absolute_error_p95": skin_sorted[p95],
                "skin_absolute_error_monte_carlo_se": statistics.stdev(skin_errors)
                / math.sqrt(NOISE_REPLICATES),
            }
        )
    means = [r["kh_relative_error_mean"] for r in rows]
    return {
        "noise_model": "additive, independent, zero-mean Gaussian error on pressure only",
        "signal_for_scale": {
            "drawdown_across_window_psi": clean[-1] - clean[0],
            "semilog_slope_psi_per_cycle": interpret(times, clean).slope_psi_per_cycle,
        },
        "levels": rows,
        "c9_monotone_in_sigma": means == sorted(means),
    }


# ---------------------------------------------------------------------------------
# B1.3 -- negative control
# ---------------------------------------------------------------------------------
def experiment_b1_3() -> dict[str, Any]:
    """Apply the same interpretation where the semilog approximation is invalid."""
    first = hours_at_t_d(NEGATIVE_CONTROL_T_D[0])
    last = hours_at_t_d(NEGATIVE_CONTROL_T_D[1])
    times = log_window(first, last, BASE_POINTS_PER_DECADE)
    drops = [drawdown_psi(t) for t in times]
    fit = interpret(times, drops)
    kh_error, skin_error = recovery_errors(fit)
    fitted_line = [fit.intercept_psi + fit.slope_psi_per_cycle * math.log10(t) for t in times]
    return {
        "series": {
            "time_hours": list(times),
            "dimensionless_time": [t_d(t) for t in times],
            "drawdown_psi": list(drops),
            "fitted_line_psi": fitted_line,
        },
        "window_dimensionless_time": list(NEGATIVE_CONTROL_T_D),
        "first_hour": first,
        "last_hour": last,
        "points": len(times),
        "recovery": {
            "permeability_md_recovered": fit.permeability_md,
            "permeability_thickness_relative_error": kh_error,
            "skin_recovered": fit.skin,
            "skin_absolute_error": skin_error,
        },
        # The point of the control: the fit still looks excellent.
        "r_squared": fit.r_squared,
        "residual_standard_error_psi": fit.residual_standard_error_psi,
        "looks_like_a_good_fit": fit.r_squared > 0.999,
        "c7_negative_control_fails_c3": kh_error > C7_NEGATIVE_CONTROL_MIN_KH_ERROR,
        "also_misses_the_looser_plan_target_of_five_percent": kh_error > 0.05,
    }


def collect_criteria(results: dict[str, Any]) -> dict[str, bool]:
    """Pull the pre-registered acceptance flags out of the experiment payloads."""
    base = results["b1_0_mathematical_baseline"]
    return {
        "C1_forward_matches_oracle": bool(base["c1_forward_matches_oracle"]),
        "C2_constants_reproduce": bool(base["c2_constants_reproduce"]),
        "C3_permeability_thickness_recovered": bool(base["c3_kh_recovered"]),
        "C4_skin_recovered": bool(base["c4_skin_recovered"]),
        "C5_derivative_matches_closed_form": bool(base["c5_derivative_matches_closed_form"]),
        "C6_plateau_below_ideal_half": bool(base["c6_plateau_below_ideal_half"]),
        "C7_negative_control_fails": bool(results["b1_3_negative_control"]["c7_negative_control_fails_c3"]),
        "C9_noise_degradation_monotone": bool(results["b1_2_pressure_noise"]["c9_monotone_in_sigma"]),
    }


# ---------------------------------------------------------------------------------
# Diagnostic D1 -- which analyst errors are visible without the truth
# ---------------------------------------------------------------------------------
# POST-HOC AND UNGATED. Not pre-registered, not an acceptance criterion, and it moves no
# threshold. It exists because "the instrument recovers the known answer" is a claim about
# a defect class, and a claim about a defect class is worth nothing until the class is
# measured. Every row below is the SAME synthetic data; only the interpretation is wrong.
#
# Each seeded defect is scored twice. Against the truth, which only this case has. And
# against the two things an analyst has WITHOUT the truth: the fit's r-squared, and whether
# the derivative plateau agrees with the kh the regression reports -- both computed with
# the analyst's own, possibly wrong, metadata, because that is the only version of the
# check a real interpretation can actually run.
def diagnostic_defect_visibility() -> dict[str, Any]:
    """Seed analyst errors into a perfect interpretation and record what shows."""

    def scored(times: list[float], drops: list[float], **overrides: float) -> dict[str, Any]:
        metadata = {
            "thickness_ft": TRUTH["thickness_ft"],
            "rate_stb_per_day": TRUTH["rate_stb_per_day"],
            "formation_volume_factor": TRUTH["formation_volume_factor"],
            "viscosity_cp": TRUTH["viscosity_cp"],
            "porosity": TRUTH["porosity"],
            "total_compressibility_per_psi": TRUTH["total_compressibility_per_psi"],
            "wellbore_radius_ft": TRUTH["wellbore_radius_ft"],
        }
        metadata.update(overrides)
        fit = semilog_interpretation(times, drops, **metadata)
        # What the analyst would report: their own recovered k times their own assumed h.
        reported_kh = fit.permeability_md * metadata["thickness_ft"]
        _, derivative_values = bourdet_derivative(times, drops, smoothing_l=SMOOTHING_L)
        observed_plateau = max(derivative_values)
        implied_plateau = (
            derivative_plateau_constant()
            * metadata["rate_stb_per_day"]
            * metadata["viscosity_cp"]
            * metadata["formation_volume_factor"]
            / reported_kh
        )
        true_kh = TRUTH["permeability_md"] * TRUTH["thickness_ft"]
        return {
            "permeability_thickness_relative_error": abs(reported_kh - true_kh) / true_kh,
            "permeability_relative_error": abs(fit.permeability_md - TRUTH["permeability_md"])
            / TRUTH["permeability_md"],
            "skin_absolute_error": abs(fit.skin - TRUTH["skin"]),
            "r_squared": fit.r_squared,
            "derivative_versus_fit_relative_difference": abs(observed_plateau - implied_plateau)
            / implied_plateau,
        }

    def window(start_t_d: float, ratio: float = 48.0, per_decade: int = BASE_POINTS_PER_DECADE):
        first = hours_at_t_d(start_t_d)
        times = log_window(first, first * ratio, per_decade)
        return times, [drawdown_psi(x) for x in times]

    base_times = log_window(WINDOW_FIRST_HOUR, WINDOW_LAST_HOUR, BASE_POINTS_PER_DECADE)
    base_drops = [drawdown_psi(x) for x in base_times]
    declared_t_d = t_d(WINDOW_FIRST_HOUR)

    rows: list[dict[str, Any]] = [
        {"defect": "none (baseline)", "kind": "reference", **scored(base_times, base_drops)},
        {"defect": "window starts at t_D = 10", "kind": "window", **scored(*window(10.0))},
        {
            "defect": "duration one third of a decade",
            "kind": "window",
            **scored(*window(declared_t_d, ratio=2.15)),
        },
        {
            "defect": "two points per decade",
            "kind": "sampling",
            **scored(*window(declared_t_d, per_decade=2)),
        },
        {
            "defect": "time zero wrong by +0.5 hour",
            "kind": "data",
            **scored([x + 0.5 for x in base_times], base_drops),
        },
        {
            "defect": "drawdown sign flipped",
            "kind": "data",
            **scored(base_times, [-x for x in base_drops]),
        },
        {
            "defect": "rate 1.589x wrong (m3/d read as STB/D)",
            "kind": "metadata",
            **scored(base_times, base_drops, rate_stb_per_day=TRUTH["rate_stb_per_day"] * 1.589873),
        },
        {
            "defect": "net thickness 1.5x too large",
            "kind": "metadata",
            **scored(base_times, base_drops, thickness_ft=TRUTH["thickness_ft"] * 1.5),
        },
        {
            "defect": "radius entered as diameter",
            "kind": "metadata",
            **scored(base_times, base_drops, wellbore_radius_ft=TRUTH["wellbore_radius_ft"] * 2.0),
        },
        {
            "defect": "porosity 0.18 read as 0.25",
            "kind": "metadata",
            **scored(base_times, base_drops, porosity=0.25),
        },
        {
            "defect": "viscosity 1.2 read as 0.9 cp",
            "kind": "metadata",
            **scored(base_times, base_drops, viscosity_cp=0.9),
        },
    ]

    baseline = rows[0]
    # A defect counts as visible only if it moves a diagnostic well clear of where that
    # diagnostic already sits on a clean interpretation. Ten times the baseline floor is a
    # deliberately generous bar, and six of the ten defects still do not clear it.
    for row in rows[1:]:
        row["visible_without_truth"] = (
            row["r_squared"] < baseline["r_squared"] - 1e-6
            or row["derivative_versus_fit_relative_difference"]
            > 10.0 * baseline["derivative_versus_fit_relative_difference"]
        )
        row["materially_wrong"] = (
            row["permeability_thickness_relative_error"] > C3_KH_RELATIVE
            or row["permeability_relative_error"] > C3_KH_RELATIVE
            or row["skin_absolute_error"] > C4_SKIN_ABSOLUTE
        )

    silent_and_wrong = [
        row["defect"] for row in rows[1:] if row["materially_wrong"] and not row["visible_without_truth"]
    ]
    return {
        "note": (
            "Post-hoc, ungated. Measures the defect class the acceptance criteria can "
            "actually see. No threshold in this block gates the run."
        ),
        "rows": rows,
        "silent_but_materially_wrong": silent_and_wrong,
        "silent_but_materially_wrong_count": len(silent_and_wrong),
    }


# ---------------------------------------------------------------------------------
# Diagnostic D2 -- what smoothing L costs on noise-free data
# ---------------------------------------------------------------------------------
def diagnostic_smoothing_cost() -> dict[str, Any]:
    """POST-HOC AND UNGATED. Derivative accuracy against L, where the answer is exact."""
    times = log_window(WINDOW_FIRST_HOUR, WINDOW_LAST_HOUR, BASE_POINTS_PER_DECADE)
    drops = [drawdown_psi(x) for x in times]
    scale = pressure_drop_psi(
        1.0,
        permeability_md=TRUTH["permeability_md"],
        thickness_ft=TRUTH["thickness_ft"],
        rate_stb_per_day=TRUTH["rate_stb_per_day"],
        formation_volume_factor=TRUTH["formation_volume_factor"],
        viscosity_cp=TRUTH["viscosity_cp"],
    )
    rows = []
    for smoothing in (0.0, 0.02, 0.05, 0.1, 0.2, 0.3, 0.5):
        deriv_times, deriv_values = bourdet_derivative(times, drops, smoothing_l=smoothing)
        analytic = [line_source_log_derivative(t_d(x)) * scale for x in deriv_times]
        rows.append(
            {
                "smoothing_l": smoothing,
                "points": len(deriv_values),
                "max_relative_error_against_closed_form": max(
                    abs(v - a) / a for v, a in zip(deriv_values, analytic, strict=True)
                ),
            }
        )
    return {
        "note": (
            "Post-hoc, ungated. On noise-free data smoothing only costs accuracy; its "
            "value is entirely in the noisy case, which this block does not exercise."
        ),
        "rows": rows,
    }


def main(argv: list[str] | None = None) -> int:
    """Run case B1 into a fresh directory and write its summary."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="fresh run directory")
    args = parser.parse_args(argv)

    config = {
        "truth": dict(TRUTH),
        "window_first_hour": WINDOW_FIRST_HOUR,
        "window_last_hour": WINDOW_LAST_HOUR,
        "points_per_decade": BASE_POINTS_PER_DECADE,
        "smoothing_l": SMOOTHING_L,
        "noise_sigmas_psi": list(NOISE_SIGMAS_PSI),
        "noise_replicates": NOISE_REPLICATES,
        "noise_seed_base": NOISE_SEED_BASE,
        "protocol": {
            "path": "cases/B1_iarf_known_answer/protocol.md",
            "commit": PROTOCOL_COMMIT,
            "blob_digest": protocol_digest(),
        },
        "thresholds": {
            "C1_forward_oracle_relative": C1_FORWARD_ORACLE_RELATIVE,
            "C2_constant_relative": C2_CONSTANT_RELATIVE,
            "C3_kh_relative": C3_KH_RELATIVE,
            "C4_skin_absolute": C4_SKIN_ABSOLUTE,
            "C5_derivative_relative": C5_DERIVATIVE_RELATIVE,
            "C7_negative_control_min_kh_error": C7_NEGATIVE_CONTROL_MIN_KH_ERROR,
        },
    }

    with RunRecord.open(
        args.out,
        label=CASE_ID,
        config=config,
        seed=NOISE_SEED_BASE,
        settings={
            "python_float": "IEEE 754 binary64",
            "dependencies": "standard library only",
            "protocol": "cases/B1_iarf_known_answer/protocol.md",
        },
        repo_root=".",
    ) as record:
        results: dict[str, Any] = {
            "b1_0_mathematical_baseline": experiment_b1_0(),
            "b1_1_sampling_and_placement": experiment_b1_1(),
            "b1_2_pressure_noise": experiment_b1_2(),
            "b1_3_negative_control": experiment_b1_3(),
            "diagnostic_defect_visibility": diagnostic_defect_visibility(),
            "diagnostic_smoothing_cost": diagnostic_smoothing_cost(),
        }
        criteria = collect_criteria(results)
        payload: dict[str, Any] = {
            "case_id": CASE_ID,
            "case_type": "synthetic",
            "config": config,
            **results,
            "criteria": criteria,
            "all_criteria_met": all(criteria.values()),
            "limitations": list(LIMITATIONS),
        }
        payload["metrics_sha256"] = canonical_hash(results)
        record.write_json("summary.json", payload)
        record.metrics(
            permeability_thickness_relative_error=results["b1_0_mathematical_baseline"]["recovery"][
                "permeability_thickness_relative_error"
            ],
            skin_absolute_error=results["b1_0_mathematical_baseline"]["recovery"]["skin_absolute_error"],
            negative_control_kh_relative_error=results["b1_3_negative_control"]["recovery"][
                "permeability_thickness_relative_error"
            ],
        )

    base = results["b1_0_mathematical_baseline"]["recovery"]
    print(f"B1 -- {CASE_ID}")
    print(
        f"  kh      true {base['permeability_thickness_true']:.6g} md.ft, "
        f"recovered {base['permeability_thickness_recovered']:.9g}, "
        f"relative error {base['permeability_thickness_relative_error']:.3e}"
    )
    print(
        f"  skin    true {base['skin_true']:.6g}, recovered {base['skin_recovered']:.9g}, "
        f"absolute error {base['skin_absolute_error']:.3e}"
    )
    neg = results["b1_3_negative_control"]["recovery"]
    print(
        f"  negative control kh relative error {neg['permeability_thickness_relative_error']:.3e} "
        f"(must exceed {C7_NEGATIVE_CONTROL_MIN_KH_ERROR:.0e})"
    )
    for name, met in criteria.items():
        print(f"  {'PASS' if met else 'FAIL'}  {name}")
    return 0 if all(criteria.values()) else 1


if __name__ == "__main__":
    sys.exit(main())
